### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by jlesquembre** [mhinz/vim-halo#2]
I have this line on my `vimrc` config:

```
nnoremap <silent><expr> n 'Nn'[v:searchforward] . ':call halo#run()<cr>'
```

If I do a search, and I press `n` fast enough (when the line is still blinking), I get a 'list index out of range' error, and the last line highlighted is not cleared. I tested it on neovim 0.1.6.

I tried to fix it with this commit: [link](https://github.com/jlesquembre/vim-halo/commit/1ffb758c29b7ffb719b15a3096ff761e96648791)

Seems to work, but is not the best solution.

**Comment by mhinz** [comment]
Yea, I think that solution only works by accident. :-) In general, two concurrently running functions should never access the same variable, if there's no guarantee that it hasn't changed in the meanwhile.

E.g. if `show()` is called concurrently two times, the second `let s:halo_id = matchaddpos()` line would overwrite the first one and by the time both `hide()` calls are executed they will try to `matchdelete()` the same second ID and forgot about the first one. Typical race condition.

Since `timer_start()` doesn't allow to provide arguments to its referenced functions, the optimal solution would be to wrap each `halo#run()` into its own isolated environment.

In Vim that already works by either using Dictionary functions or using Partials. Implementing that is WIP for Neovim at the moment.

I created a new branch, [objectify](https://github.com/mhinz/vim-halo/blob/b77f02c1e488b92d16902aaea0f1c1b823f86ffb/autoload/halo.vim#L42-L63), as proof of concept. That branch works in (a recent) Vim, but not in Neovim yet.

---

**I keep this issue open until Partial support lands in Neovim.**

**Comment by justinmk** [comment]
@mhinz This can be closed, right?
